# Install Library

In [1]:
!pip install google-play-scraper

Collecting google-play-scraper
  Downloading google_play_scraper-1.2.7-py3-none-any.whl.metadata (50 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.2/50.2 kB 2.3 MB/s eta 0:00:00
Downloading google_play_scraper-1.2.7-py3-none-any.whl (28 kB)
Installing collected packages: google-play-scraper
Successfully installed google-play-scraper-1.2.7

In [2]:
!pip install pandas
!pip install numpy

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)

In [3]:
from google_play_scraper import app
import pandas as pd
import numpy as np

In [11]:
#scrape all available reviews
from google_play_scraper import Sort, reviews

result, continuation_token = reviews(
'com.whatsapp',
lang = 'id',
country ='id',
sort=Sort.NEWEST,
count=10000,
filter_score_with=None

)

In [12]:
df_busu = pd.DataFrame(np.array(result),columns=['review'])
df_busu = df_busu.join(pd.DataFrame(df_busu.pop('review').tolist()))
df_busu.tail()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
9995,854d4524-954b-4f85-bd6f-12742c18d023,aulia irdina,https://play-lh.googleusercontent.com/a-/ALV-U...,Berjalan lancar dan Please remove gif picture ...,5,0,2.26.19.73,2026-05-24 02:56:21,None,None,2.26.19.73
9996,1ecf5fa2-05a0-4982-9ee7-7616e1340e11,Aurora7ra,https://play-lh.googleusercontent.com/a/ACg8oc...,kadang lag,4,0,None,2026-05-24 02:53:24,None,None,None
9997,dc9316c4-f4da-4fef-a657-c47763c8e41d,Putra Aja,https://play-lh.googleusercontent.com/a/ACg8oc...,whtasap makin buruk,1,0,2.26.19.73,2026-05-24 02:53:03,None,None,2.26.19.73
9998,d2c92485-42bf-483b-b7f6-ede9a4b546f0,Alim Arjuna,https://play-lh.googleusercontent.com/a/ACg8oc...,Bagus 👍,5,0,2.26.8.72,2026-05-24 02:52:39,None,None,2.26.8.72
9999,39c06cee-d820-4c14-828b-f7ddc7b56ae2,leo ryan,https://play-lh.googleusercontent.com/a-/ALV-U...,serba praktiss👍👍,5,0,2.26.19.73,2026-05-24 02:49:09,None,None,2.26.19.73

#ambil data yang dibutuhkan

In [13]:
df_busu[['userName', 'score', 'at', 'content']].tail()

,userName,score,at,content
9995,aulia irdina,5,2026-05-24 02:56:21,Berjalan lancar dan Please remove gif picture ...
9996,Aurora7ra,4,2026-05-24 02:53:24,kadang lag
9997,Putra Aja,1,2026-05-24 02:53:03,whtasap makin buruk
9998,Alim Arjuna,5,2026-05-24 02:52:39,Bagus 👍
9999,leo ryan,5,2026-05-24 02:49:09,serba praktiss👍👍

In [14]:
my_df = df_busu[['userName', 'score', 'at', 'content']]

In [ ]:
#simpan dataset ke dalam file   
my_df.to_csv("DataSetWhatsApp.csv",index = False)