In [2]:
!pip install pandas
!pip install  numpy
!pip install nltk

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.4.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.3)

In [4]:
#untuk komputasi numerik
import numpy as np

#memproses pengolahan teks
import nltk

#membantu mempermudah manipulasi data teks
import string

#hilangkan notif karena migrasi dari python
import warnings
warnings.filterwarnings('ignore')

#New Section

In [5]:
#import Library yang dubutuhkan
import pandas as pd
from tqdm import tqdm,notebook
import warnings
warnings.filterwarnings('ignore')

pd.pandas.set_option('display.max_columns',None)
pd.pandas.set_option('display.max_rows',None)
pd.pandas.set_option('display.max_colwidth',None)
pd.pandas.set_option('display.width',None)

In [7]:
df = pd.read_csv('/content/DataSetWhatsApp.csv')
df.head()

,userName,score,at,content
0,Pengguna Google,4,2026-06-01 04:14:48,WhatsAppnya bagus updet dong tapi aku suka bisa dibuat telefon wa dan juga lain lainya
1,Pengguna Google,3,2026-06-01 04:14:08,"Tolong tingkatkan kualitas builtin whatsapp sticker soalnya, 1. ketika buat stiker dari gambar itu ada border putih dan menjadi squircle dan kami tidak suka ini 2. kualitas sticker menjadi low quality 3. tool di sticker maker builtin kurang, 4. ai jelek 5. setiap kali edit sebuah stiker kualitas menurun 6. aku muak dengan orang yang pakai stiker builtin whatsapp jadi aku kasih bintang 3"
2,Pengguna Google,5,2026-06-01 04:13:29,Bagus pelayananya saya dukung
3,Pengguna Google,1,2026-06-01 04:10:20,fitur terbarunya bikin susah saat vc
4,Pengguna Google,3,2026-06-01 04:09:07,"aneh yaa padahal jaringan sama"" bagus, tapi ntah kenaap pas vc sering lag"" gajelass, tolong diperbaiki lah"

In [9]:
df['sentimen'] = df['score'].map({1.0:0,2.0:0,3.0:1, 4.0:1, 5.0:1})

In [11]:
#ambil teks aja untuk kita labelkan
dataku = pd.DataFrame(df[['content','sentimen']])
dataku.head(10)

,content,sentimen
0,WhatsAppnya bagus updet dong tapi aku suka bisa dibuat telefon wa dan juga lain lainya,1
1,"Tolong tingkatkan kualitas builtin whatsapp sticker soalnya, 1. ketika buat stiker dari gambar itu ada border putih dan menjadi squircle dan kami tidak suka ini 2. kualitas sticker menjadi low quality 3. tool di sticker maker builtin kurang, 4. ai jelek 5. setiap kali edit sebuah stiker kualitas menurun 6. aku muak dengan orang yang pakai stiker builtin whatsapp jadi aku kasih bintang 3",1
2,Bagus pelayananya saya dukung,1
3,fitur terbarunya bikin susah saat vc,0
4,"aneh yaa padahal jaringan sama"" bagus, tapi ntah kenaap pas vc sering lag"" gajelass, tolong diperbaiki lah",1
5,knp wa baru 1x chat ke blockir,0
6,sangat mudah,1
7,kecewa yuk..tumbal..tuman keseruan..nebak.. pemerintah pusat yang khusus Garut.. Gendo gembong PKI.. KSH,1
8,kenapa no aku di keluarkan terus,1
9,tidak ada iklannya,1

In [12]:
my_df = dataku[['content','sentimen']]

In [13]:
#simpan dataset ke dalam file
my_df.to_csv("DataSetWhatsApp.csv",index = False)